name: Devlog Front Matter
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fix:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm run fix:devlog || true
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Normalize devlog front matter (auto)"
            git push
          else
            echo "No changes."
          fi
