title: OXI Docs
baseurl: /OXI-DOCS
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
collections:
  concepts:
    output: true
  unity:
    output: true
  tutorials:
    output: true
  devlog:
    output: true
  changelog:
    output: true
