title: OXI-DOCS
baseurl: /OXI-DOCS
permalink: pretty
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
collections:
  concepts:
    output: true
  unity:
    output: true
  tutorials:
    output: true
  devlog:
    output: true
    permalink: /devlog/:slug/
  changelog:
    output: true

feed:
  collections:
    - devlog

defaults:
  - scope:
      path: "_devlog"
      type: "devlog"
    values:
      layout: post
      tags: ["devlog"]
